FROM rust:1.85-alpine AS builder

RUN apk add --no-cache musl-dev gcc make cmake ninja perl coreutils aarch64-linux-musl-gcc
RUN rustup target add aarch64-unknown-linux-musl

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc
ENV CC_aarch64_unknown_linux_musl=aarch64-linux-musl-gcc

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN cargo build --release --target=aarch64-unknown-linux-musl

FROM registry.it.iakl.top/alpine:3.22

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=builder /app/target/aarch64-unknown-linux-musl/release/nexapipe /usr/local/bin/nexapipe

EXPOSE 80 443 8080 8081

ENTRYPOINT ["nexapipe"]
CMD ["--config", "/app/config.toml"]
